### ISSUE TITLE
Remove tag <a> use <button> instead .

### ISSUE THREAD

**Issue by artmarydotir** [fatemeh-ta/Mosalas#28]
https://github.com/fatemeh-ta/Mosalas/blob/ae3c95c87d5050a4943ba3c872cc2d370a3ef0b6/index.html#L74
****

search box should have form element.
```

<form class="bala-bla-blaa">
       <input placeholder="جستجو" type="text" value="جستجو">
        <button type="submit" id="search-submit">
            <i class="fa fa-search"></i>
        </button>
</form>
```

**Comment by fatemeh-ta** [comment]
excuse me,I don't understand class name:

< class="bala-bla-blaa">
